name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: update apt-get
      run: sudo apt-get update

    - name: Setup Flutter SDK
      uses: flutter-actions/setup-flutter@v4
      with:
        channel: stable

    - name: Install dependencies & building
      run: flutter build web

    - name: Remove old files in the bucket
      run: aws s3 rm s3://poc-flutter-pawa-mine/ --recursive
      env:
        AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID}}'
        AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY}}'
        AWS_DEFAULT_REGION: eu-west-3

    - name: Push new files in the bucket
      run: aws s3 cp build/web/ s3://poc-flutter-pawa-mine/ --recursive
      env:
        AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID}}'
        AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY}}'
        AWS_DEFAULT_REGION: eu-west-3